# Generated by Django 6.0.7 on 2026-07-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_tickets', 'Can manage tickets')]},
        ),
    ]
